// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxMCSPqnmlTx5QsTUkwFXDZ4qRmS3owm8',
    appId: '1:346959556725:android:a0553f429088fbb0a0483c',
    messagingSenderId: '346959556725',
    projectId: 'bens-ways',
    storageBucket: 'bens-ways.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe3UX4sfTxh5iz1yLeXtDWXDQ7P8Ll9m0',
    appId: '1:346959556725:ios:5f5544156287df28a0483c',
    messagingSenderId: '346959556725',
    projectId: 'bens-ways',
    storageBucket: 'bens-ways.firebasestorage.app',
    iosBundleId: 'com.example.bensWays',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCksf98K55yy0KjlpFBqxGtzSxK2DbS7mw',
    appId: '1:346959556725:web:a82f420a63d9c309a0483c',
    messagingSenderId: '346959556725',
    projectId: 'bens-ways',
    authDomain: 'bens-ways.firebaseapp.com',
    storageBucket: 'bens-ways.firebasestorage.app',
    measurementId: 'G-K76VMH9XD1',
  );

}